import { createSlice } from '@reduxjs/toolkit';

interface CountriesState {
  items: string[];
}

const initialState: CountriesState = {
  items: [
    'Albania',
    'Austria',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Czech Republic',
    'Denmark',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'Ireland',
    'Italy',
    'Latvia',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Montenegro',
    'Netherlands',
    'North Macedonia',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Ukraine',
    'United Kingdom',

    'Afghanistan',
    'Armenia',
    'Azerbaijan',
    'Bangladesh',
    'Cambodia',
    'China',
    'Georgia',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Israel',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Lebanon',
    'Malaysia',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'North Korea',
    'Oman',
    'Pakistan',
    'Philippines',
    'Qatar',
    'Saudi Arabia',
    'Singapore',
    'South Korea',
    'Sri Lanka',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Turkey',
    'Turkmenistan',
    'United Arab Emirates',
    'Uzbekistan',
    'Vietnam',

    'Algeria',
    'Angola',
    'Cameroon',
    'Chad',
    'Democratic Republic of the Congo',
    'Egypt',
    'Ethiopia',
    'Ghana',
    'Ivory Coast',
    'Kenya',
    'Libya',
    'Madagascar',
    'Mali',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Nigeria',
    'Rwanda',
    'Senegal',
    'Somalia',
    'South Africa',
    'Sudan',
    'Tanzania',
    'Tunisia',
    'Uganda',
    'Zambia',
    'Zimbabwe',

    'Canada',
    'Costa Rica',
    'Cuba',
    'Dominican Republic',
    'El Salvador',
    'Guatemala',
    'Haiti',
    'Honduras',
    'Jamaica',
    'Mexico',
    'Nicaragua',
    'Panama',
    'Puerto Rico',
    'Trinidad and Tobago',
    'United States',

    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',

    'Australia',
    'Fiji',
    'New Zealand',
    'Papua New Guinea',
    'Samoa',
    'Solomon Islands',
    'Tonga',
    'Vanuatu',
  ],
};

const countriesSlice = createSlice({
  name: 'countries',
  initialState,
  reducers: {},
});

export const countriesReducer = countriesSlice.reducer;
